2024-03-18 02:28:09,454 - INFO [Resource,0 1 rpc::initialize] Established connection with localhost:29000 (LogService,0) (local address: 127.0.0.1:36186).
2024-03-18 02:28:09,458 - INFO [Resource,0 Main service::run] ResourceService 0 up and running!
2024-03-18 02:28:09,467 - INFO [Resource,0 2 ResourceService::_restart_services] Restarting (Checker, 0)...
2024-03-18 02:28:09,477 - ERROR [Resource,0 2 ResourceService::_restart_services] Error for command line './scripts/cmsChecker 0 -c 2'
2024-03-18 02:28:09,477 - ERROR [Resource,0 2 service::repeater] Unexpected error.
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/cms-1.4rc1-py3.10.egg/cms/io/service.py", line 80, in repeater
    func()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/cms-1.4rc1-py3.10.egg/cms/service/ResourceService.py", line 273, in _restart_services
    process = subprocess.Popen(args,
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/gevent/subprocess.py", line 808, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/gevent/subprocess.py", line 1838, in _execute_child
    raise child_exception
FileNotFoundError: [Errno 2] No such file or directory: './scripts/cmsChecker'
2024-03-18 02:28:09,583 - INFO [Resource,0 3 rpc::initialize] Established connection with 127.0.0.1:53868 (local address: 127.0.0.1:28000).
2024-03-18 02:28:14,473 - INFO [Resource,0 2 ResourceService::_restart_services] Restarting (Checker, 0)...
2024-03-18 02:28:14,481 - ERROR [Resource,0 2 ResourceService::_restart_services] Error for command line './scripts/cmsChecker 0 -c 2'
2024-03-18 02:28:14,482 - ERROR [Resource,0 2 service::repeater] Unexpected error.
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/cms-1.4rc1-py3.10.egg/cms/io/service.py", line 80, in repeater
    func()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/cms-1.4rc1-py3.10.egg/cms/service/ResourceService.py", line 273, in _restart_services
    process = subprocess.Popen(args,
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/gevent/subprocess.py", line 808, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/gevent/subprocess.py", line 1838, in _execute_child
    raise child_exception
FileNotFoundError: [Errno 2] No such file or directory: './scripts/cmsChecker'
2024-03-18 02:28:15,938 - WARNING [Resource,0 5 service::exit] ResourceService,0 received request to shut down.
2024-03-18 02:28:15,939 - INFO [Resource,0 Main service::run] ResourceService 0 is shutting down
2024-03-18 02:28:15,940 - INFO [Resource,0 Main rpc::finalize] Terminated connection with localhost:29000 (LogService,0) (local address: 127.0.0.1:36186): Disconnection requested.
